import type { Tutor, Testimonial, Subject } from "@/types";

export const MOCK_TUTORS: Tutor[] = [
  {
    id: "1",
    name: "李明远",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LiMingyuan",
    subjects: ["高等数学", "线性代数", "概率论"],
    university: "北京大学",
    major: "数学系",
    grade: "研究生二年级",
    hourlyRate: 120,
    rating: 4.9,
    reviewCount: 87,
    bio: "北大数学系研究生，擅长将复杂概念用简单方式讲解，已帮助 80+ 学生通过期末考试。",
    tags: ["耐心细致", "逻辑清晰", "备考专家"],
    available: true,
  },
  {
    id: "2",
    name: "张雨晴",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ZhangYuqing",
    subjects: ["大学英语", "英语写作", "雅思备考"],
    university: "复旦大学",
    major: "英语语言文学",
    grade: "大四",
    hourlyRate: 100,
    rating: 4.8,
    reviewCount: 63,
    bio: "雅思 8.0，CET-6 满分，专注英语口语和写作提升，课程生动有趣。",
    tags: ["口语流利", "写作专家", "雅思托福"],
    available: true,
  },
  {
    id: "3",
    name: "王浩然",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=WangHaoran",
    subjects: ["C++", "数据结构", "算法"],
    university: "清华大学",
    major: "计算机科学",
    grade: "大三",
    hourlyRate: 150,
    rating: 5.0,
    reviewCount: 42,
    bio: "ACM 竞赛金牌，LeetCode 2600+，专注算法与数据结构，帮你轻松应对笔试面试。",
    tags: ["ACM金牌", "算法大神", "面试辅导"],
    available: false,
  },
  {
    id: "4",
    name: "陈思琪",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ChenSiqi",
    subjects: ["大学物理", "电磁学", "量子力学"],
    university: "中国科学技术大学",
    major: "物理学",
    grade: "研究生一年级",
    hourlyRate: 130,
    rating: 4.7,
    reviewCount: 55,
    bio: "物理竞赛全国一等奖，善于用实验和生活案例解释抽象物理概念。",
    tags: ["物理竞赛", "实验教学", "概念清晰"],
    available: true,
  },
  {
    id: "5",
    name: "刘子轩",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LiuZixuan",
    subjects: ["微观经济学", "宏观经济学", "计量经济学"],
    university: "上海交通大学",
    major: "经济学",
    grade: "大四",
    hourlyRate: 110,
    rating: 4.6,
    reviewCount: 38,
    bio: "经济学院优秀毕业生，擅长用图表和案例讲解经济学原理，期末高分保障。",
    tags: ["图表教学", "案例分析", "期末冲刺"],
    available: true,
  },
  {
    id: "6",
    name: "赵欣怡",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ZhaoXinyi",
    subjects: ["有机化学", "无机化学", "分析化学"],
    university: "南京大学",
    major: "化学系",
    grade: "研究生二年级",
    hourlyRate: 125,
    rating: 4.8,
    reviewCount: 71,
    bio: "化学竞赛省级一等奖，实验操作经验丰富，帮助学生建立系统化学知识体系。",
    tags: ["竞赛经验", "实验指导", "系统教学"],
    available: true,
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    studentName: "小林",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=student1",
    content: "李明远老师讲高数真的太厉害了！原来听不懂的极限和微分，上了两节课就全明白了，期末考了 92 分！",
    rating: 5,
    subject: "高等数学",
  },
  {
    id: "2",
    studentName: "阿杰",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=student2",
    content: "张雨晴老师的英语课超级有趣，口语练习很实用，雅思从 6.0 提升到 7.5，感谢！",
    rating: 5,
    subject: "雅思备考",
  },
  {
    id: "3",
    studentName: "小美",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=student3",
    content: "平台找家教很方便，老师资质都有认证，上课前可以免费试听，非常靠谱！",
    rating: 5,
    subject: "大学物理",
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  { id: "math", name: "数学", icon: "📐", tutorCount: 128 },
  { id: "english", name: "英语", icon: "🌍", tutorCount: 96 },
  { id: "cs", name: "计算机", icon: "💻", tutorCount: 84 },
  { id: "physics", name: "物理", icon: "⚛️", tutorCount: 72 },
  { id: "chemistry", name: "化学", icon: "🧪", tutorCount: 61 },
  { id: "economics", name: "经济学", icon: "📊", tutorCount: 55 },
  { id: "chinese", name: "语文", icon: "📝", tutorCount: 48 },
  { id: "biology", name: "生物", icon: "🧬", tutorCount: 43 },
];
